keys:
  - &cerberus age1gx7su7zme0e3fqfsgjydmnkdmmlpzumlc82fvl4syvjj9tsc6dqs8c67x4
  - &luna age1s06vgtmyp888xrfnnzc885t95cedey99ff33yds7x2n8fkdyk4pqctsddj
  - &thor age16726j7ylq4mn7fny20vs5xhxysg35ewfwqrkydmpgw78cdu3xqzs0ywcg2
  - &sherlock age1n0xlcm7h9m0644hpe89k5jv3ac9zlenkx2yx020sgs6ml3u6dfmq863vmw
  - &darwin age10x9vw80j88c47sr9nc96nen2ft30jg2p9u5a7ec5nl4cw3znduksedq5uu
  - &tachi age1qajz2uu85t5u3ptuzhphp0439kg8jw0cxa0c5nqw4qkpr402vetsxw9wrl
  - &dauntless age1yj88d45sjqz4y8kg0rhs2m4ek3cdvhvnqa88edkfs4ekd3wyzduq4pps3n
  - &ghost age1wtecvfxxjk38uj438rzv8xxayjxthl0l2v5usk2yxxm34ggmpp4s32qwnh
  - &work age1gpqqrzyg0dw9fg2s2tq3epsrh8rx4ylh7qww4rsnffuf2n4ynpqsyf87du
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *cerberus
          - *luna
          - *thor
          - *sherlock
          - *tachi
          - *darwin
          - *dauntless
          - *ghost
          - *work
  - path_regex: hosts/luna/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *darwin
  - path_regex: hosts/sherlock/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *sherlock
          - *darwin
  - path_regex: hosts/tachi/secrets.yaml$
    key_groups:
      - age:
          - *tachi
          - *darwin
  - path_regex: hosts/cerberus/secrets.yaml$
    key_groups:
      - age:
          - *cerberus
          - *darwin
  - path_regex: hosts/thor/secrets.yaml$
    key_groups:
      - age:
          - *thor
          - *darwin
