keys:
  - &luna age1xtkksgkn77x0cn5rq3q0jzvyn3negmu70e960xuk9felfy8eeefq75lpcf
  - &thor age16726j7ylq4mn7fny20vs5xhxysg35ewfwqrkydmpgw78cdu3xqzs0ywcg2
  - &sherlock age1n0xlcm7h9m0644hpe89k5jv3ac9zlenkx2yx020sgs6ml3u6dfmq863vmw
  - &knox age1mjg69pwlyg9l7afvmpjadx5s3u4gnwfa0mjpchaqka9k9uwtpfes2s5f6u
  - &darwin age10x9vw80j88c47sr9nc96nen2ft30jg2p9u5a7ec5nl4cw3znduksedq5uu
  - &tachi age1qajz2uu85t5u3ptuzhphp0439kg8jw0cxa0c5nqw4qkpr402vetsxw9wrl
  - &dauntless age1yj88d45sjqz4y8kg0rhs2m4ek3cdvhvnqa88edkfs4ekd3wyzduq4pps3n
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *thor
          - *sherlock
          - *tachi
          - *knox
          - *darwin
          - *dauntless
  - path_regex: hosts/luna/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *darwin
  - path_regex: hosts/sherlock/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *sherlock
          - *darwin
  - path_regex: hosts/tachi/secrets.yaml$
    key_groups:
      - age:
          - *tachi
          - *darwin
