keys:
  - &luna age1xtkksgkn77x0cn5rq3q0jzvyn3negmu70e960xuk9felfy8eeefq75lpcf
  - &thor age16726j7ylq4mn7fny20vs5xhxysg35ewfwqrkydmpgw78cdu3xqzs0ywcg2
  - &sherlock age1n0xlcm7h9m0644hpe89k5jv3ac9zlenkx2yx020sgs6ml3u6dfmq863vmw
  - &caddytor01 age19f093z4zwej5gwe96c340fycjapvqnk5zjauep0xpnguyyxpzylqt62kak
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *thor
          - *sherlock
          - *caddytor01
