keys:
  - &luna age1xtkksgkn77x0cn5rq3q0jzvyn3negmu70e960xuk9felfy8eeefq75lpcf
  - &thor age16726j7ylq4mn7fny20vs5xhxysg35ewfwqrkydmpgw78cdu3xqzs0ywcg2
  - &sherlock age1n0xlcm7h9m0644hpe89k5jv3ac9zlenkx2yx020sgs6ml3u6dfmq863vmw
  - &knox age1mjg69pwlyg9l7afvmpjadx5s3u4gnwfa0mjpchaqka9k9uwtpfes2s5f6u
  - &darwin age10x9vw80j88c47sr9nc96nen2ft30jg2p9u5a7ec5nl4cw3znduksedq5uu
  - &tachi age1e2kq2k4wpp0ncx2xx386md8a8t8upavgehugn08jlqazth43w3ws5zy5tx
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *thor
          - *sherlock
          - *tachi
          - *knox
          - *darwin
  - path_regex: hosts/luna/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *darwin
  - path_regex: hosts/sherlock/secrets.yaml$
    key_groups:
      - age:
          - *luna
          - *sherlock
          - *darwin
  - path_regex: hosts/tachi/secrets.yaml$
    key_groups:
      - age:
          - *tachi
          - *darwin
  - path_regex: modules/tailscale_key.yaml$
    key_groups:
      - age:
          - *luna
          - *thor
          - *sherlock
          - *tachi
          - *knox
          - *darwin
