# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.kernelParams = ["xe.force_probe=46a6" "i915.force_probe=!46a6"];
  boot.extraModulePackages = [
    (config.boot.kernelPackages.callPackage (
      {
        stdenv,
        fetchFromGitHub,
        kernel,
      }:
        stdenv.mkDerivation rec {
          name = "i915-sriov-dkms-${version}";
          version = "2026.03.05.2";
          src = fetchFromGitHub {
            owner = "strongtz";
            repo = "i915-sriov-dkms";
            rev = version;
            hash = "sha256-8WhfF52gXzmNhZJ7BN2C+DD89fOi/3HcszafOrXn+50=";
          };
          nativeBuildInputs = kernel.moduleBuildDependencies;
          makeFlags = [
            "-C"
            "${kernel.dev}/lib/modules/${kernel.modDirVersion}/build"
            "M=$(PWD)"
            "modules"
          ];
          installPhase = ''
            find . -name "*.ko" -exec install -Dm644 {} $out/lib/modules/${kernel.modDirVersion}/kernel/drivers/gpu/drm/i915/{} \;
          '';
        }
    ) {})
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/386925dd-8628-42ca-b2fe-53ce05b7f92d";
    fsType = "ext4";
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/18811a22-1b06-4605-a504-5c86ef51ba89";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f67cb9cb-27f7-4519-b993-aeb08e6298fc";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
